{% set name = "lua-luafilesystem" %}
{% set version = "1.8.0" %}

package:
  name: {{ name }} 
  version: {{ version }}

source:
  url: https://github.com/keplerproject/luafilesystem/archive/refs/tags/v1_8_0.tar.gz
  sha256: 16d17c788b8093f2047325343f5e9b74cccb1ea96001e45914a58bbae8932495

build:
  number: 0
  ## osx lua build is broken, see https://github.com/conda-forge/lua-feedstock/pull/40
  skip: true  # [not linux]
  rpaths:
    - lib/lua/5.4/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - luarocks
    - zlib
    - lua
  run:
    - luarocks
    - lua    

test:
  commands:
    - lua -e "require 'lfs'"

about:
  home: 'https://keplerproject.github.io/luafilesystem/'
  license: MIT
  license_family: MIT
  license_file: LICENSE 
  summary: 'File System Library for the Lua Programming Language'
  description: |
       LuaFileSystem is a Lua library developed to complement the set of 
       functions related to file systems offered by the standard Lua distribution.
       LuaFileSystem offers a portable way to access the underlying directory structure and file attributes.
       LuaFileSystem is free software and uses the same license as Lua 5.x (MIT).

extra:
  recipe-maintainers:
    - jerowe
    - izahn
