# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Wsxvc7cgYynq6qWmfnzY3xpLlejULhKC5vTpCfFPJihL/XJPDRCdcVhO451pNWJqDJsQb9YavWygm/JWZ8tn78JX9lCnOeaNt5qZnGuXlZhBeInQonRdoSW/T7F0TBtFzIgJ7XHCrFJATMAP4rC7dI+pXWe6utnZz+Sk4Rro98iQEuMsoxYLMzvmA3qOTef8UfZQy+IIsSjNrXkhRWjiPU8fgbkJTwxg6PdlxecqRyHCjLgxZkocfNXpf7sK0hp61nMd5GTpKkUg2pVp+YrreNCm68DOMO3c5t8IG9fIA3BOErKbDs9olNpQdrgdmqhpFE03qhvs4waLKOuh947mt2ZypOz99Z2T8Jz7Du8gPsXcz7f+bJDXpdXP9p/r0WeDvfGRP+5shJiMoBCvknR+Gx78RZwqbKJUtCVyqHLsniq8Cj3/0q7GHq+zkpoPC5LvB0qqPi3+XmNIAHnEZSzb7olVPym3eDSOvDCgIL7ET7VELkub9oRhPsBi8gqSNDRAKtJZWX5sd2+7alXrbDg3B2Hj7KvZ5/YbAqyUJvo7+3XN8xy4D+1Oqgtc5YNAgk4Y3OFio7SgnOyc1vzPR4snBNkYZMhDZWT0Fz2G07+PertIlQjuoujXZoVDqQ4FBWn7fiPgbS4Alri15Wa7BkfyXkvzc8pRBeTlX8CC5XcTX78="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
