# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "QGtwZ6moya0rMY2+KyGVcuF7+MTsPh37YKi8eRrofb/NRDgZj0kaXPN0zc8NFfkLdSzVQPLAZ07DBL0yMCbj7vVVQx+CfX1WnqnG8zumr0VjJ7fB92Hp11EScbrEtwhbYl1T4bMwPUQtX154fxBr7GJnTmHCBZivydllxtLPIIozXdvRq+WNt6to5UjU5LNPs+bA4KexU+dvSRUH1w3swkRLfCluvarute+Y+cFGp0zhxI0M7WXCjTe7z+esuqDIO0pvXe6KSqw6QRd5LQ8rrA1TaDV5vnaKQWC1OY36e5VTm3L+XQdPxlMeT9jeaWN3VxYX12Vq1Okeu/zq6jwxiejptGvEl3uUwXlctgo4qzoxEStcFoJoG677HMLm3vl2oOeCd3Ms6Zano1LyhwOb9Cn5SttaC4zCyNHOvzA1qL8IZORrHPNUUKYlx2r2uxKA3Hl8DaQs3ddaw0DSbTaW7dIv2WHYaEbL3hMzirm1cdz7U36VSB78ZHsv6JjTTw5puoS5S5ua1dowWpW109+0JRDAO+eOVPRob9s2mJDO/P7B6YICrvse+d7p2FEjpE6iyroYcQ1fpQ6MsTPSE9W39vEUFdpnxaCTLEG2hQcCaVkV83adUZaKPKXOEQxdXH93ePRTy7KflvzytywVxR24SvXy4ju19sKkGwyh8NqASB0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml