travis:
  secure:
    BINSTAR_TOKEN: QGtwZ6moya0rMY2+KyGVcuF7+MTsPh37YKi8eRrofb/NRDgZj0kaXPN0zc8NFfkLdSzVQPLAZ07DBL0yMCbj7vVVQx+CfX1WnqnG8zumr0VjJ7fB92Hp11EScbrEtwhbYl1T4bMwPUQtX154fxBr7GJnTmHCBZivydllxtLPIIozXdvRq+WNt6to5UjU5LNPs+bA4KexU+dvSRUH1w3swkRLfCluvarute+Y+cFGp0zhxI0M7WXCjTe7z+esuqDIO0pvXe6KSqw6QRd5LQ8rrA1TaDV5vnaKQWC1OY36e5VTm3L+XQdPxlMeT9jeaWN3VxYX12Vq1Okeu/zq6jwxiejptGvEl3uUwXlctgo4qzoxEStcFoJoG677HMLm3vl2oOeCd3Ms6Zano1LyhwOb9Cn5SttaC4zCyNHOvzA1qL8IZORrHPNUUKYlx2r2uxKA3Hl8DaQs3ddaw0DSbTaW7dIv2WHYaEbL3hMzirm1cdz7U36VSB78ZHsv6JjTTw5puoS5S5ua1dowWpW109+0JRDAO+eOVPRob9s2mJDO/P7B6YICrvse+d7p2FEjpE6iyroYcQ1fpQ6MsTPSE9W39vEUFdpnxaCTLEG2hQcCaVkV83adUZaKPKXOEQxdXH93ePRTy7KflvzytywVxR24SvXy4ju19sKkGwyh8NqASB0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
