travis:
  secure:
    BINSTAR_TOKEN: Wsxvc7cgYynq6qWmfnzY3xpLlejULhKC5vTpCfFPJihL/XJPDRCdcVhO451pNWJqDJsQb9YavWygm/JWZ8tn78JX9lCnOeaNt5qZnGuXlZhBeInQonRdoSW/T7F0TBtFzIgJ7XHCrFJATMAP4rC7dI+pXWe6utnZz+Sk4Rro98iQEuMsoxYLMzvmA3qOTef8UfZQy+IIsSjNrXkhRWjiPU8fgbkJTwxg6PdlxecqRyHCjLgxZkocfNXpf7sK0hp61nMd5GTpKkUg2pVp+YrreNCm68DOMO3c5t8IG9fIA3BOErKbDs9olNpQdrgdmqhpFE03qhvs4waLKOuh947mt2ZypOz99Z2T8Jz7Du8gPsXcz7f+bJDXpdXP9p/r0WeDvfGRP+5shJiMoBCvknR+Gx78RZwqbKJUtCVyqHLsniq8Cj3/0q7GHq+zkpoPC5LvB0qqPi3+XmNIAHnEZSzb7olVPym3eDSOvDCgIL7ET7VELkub9oRhPsBi8gqSNDRAKtJZWX5sd2+7alXrbDg3B2Hj7KvZ5/YbAqyUJvo7+3XN8xy4D+1Oqgtc5YNAgk4Y3OFio7SgnOyc1vzPR4snBNkYZMhDZWT0Fz2G07+PertIlQjuoujXZoVDqQ4FBWn7fiPgbS4Alri15Wa7BkfyXkvzc8pRBeTlX8CC5XcTX78=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
